// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV8W9xIRu-8ittKGB-4rOmc3XHqoxz1PY',
    appId: '1:1078187279446:web:ede4b779b533b86ccea7f7',
    messagingSenderId: '1078187279446',
    projectId: 'rablo-chat-c444b',
    authDomain: 'rablo-chat-c444b.firebaseapp.com',
    databaseURL: 'https://rablo-chat-c444b-default-rtdb.firebaseio.com',
    storageBucket: 'rablo-chat-c444b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZmpuoKy2mOqg8BF4aq9pGA5dytDK5UYc',
    appId: '1:1078187279446:android:a3750b2c1dea00b5cea7f7',
    messagingSenderId: '1078187279446',
    projectId: 'rablo-chat-c444b',
    databaseURL: 'https://rablo-chat-c444b-default-rtdb.firebaseio.com',
    storageBucket: 'rablo-chat-c444b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4OqgQvKMMxh7rWU3ti7-NgFTkl2rMV-o',
    appId: '1:1078187279446:ios:94e571a88833bdf3cea7f7',
    messagingSenderId: '1078187279446',
    projectId: 'rablo-chat-c444b',
    databaseURL: 'https://rablo-chat-c444b-default-rtdb.firebaseio.com',
    storageBucket: 'rablo-chat-c444b.firebasestorage.app',
    iosBundleId: 'com.example.rabloChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4OqgQvKMMxh7rWU3ti7-NgFTkl2rMV-o',
    appId: '1:1078187279446:ios:94e571a88833bdf3cea7f7',
    messagingSenderId: '1078187279446',
    projectId: 'rablo-chat-c444b',
    databaseURL: 'https://rablo-chat-c444b-default-rtdb.firebaseio.com',
    storageBucket: 'rablo-chat-c444b.firebasestorage.app',
    iosBundleId: 'com.example.rabloChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV8W9xIRu-8ittKGB-4rOmc3XHqoxz1PY',
    appId: '1:1078187279446:web:eed8bac54876b797cea7f7',
    messagingSenderId: '1078187279446',
    projectId: 'rablo-chat-c444b',
    authDomain: 'rablo-chat-c444b.firebaseapp.com',
    databaseURL: 'https://rablo-chat-c444b-default-rtdb.firebaseio.com',
    storageBucket: 'rablo-chat-c444b.firebasestorage.app',
  );
}
